### PR TITLE
Refactor and simplify

### PR DESCRIPTION
**Pull request by oysteinsigholt**

### CODE REVIEW

**Comment by oysteinsigholt** [comment]
We probably should be linting the code with the TelenorFrontend conventions, but since the project was created before the conventions were, it uses the airbnb code conventions. Changing conventions/automatic linting could maybe be a different pull request?

The test is skipped because it is a test for a feature that isn't implemented yet.

**Comment by jorunfa** [comment]
1. Yes, and probably not top priority. Add issue/trello item?
2. Add a comment about it not being implemented yet?

**Comment by oysteinsigholt** [comment]
Issue and comment added.

**Comment by jorunfa** [comment]
I think it looks good then :). As I said I'm not 100% up to speed, but I think we can revisit it if we find that something is missing.

**Pull request merged**
